name: tn_bottom_sheet_navigator
description: >-
  A modal bottom sheet with internal navigation and dynamic size (height)
  based on content.
version: 0.0.10
repository: https://github.com/jordy-garcia/tn_bottom_sheet_navigator

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.10

platforms:
  android:
  ios:

funding:
  - https://buymeacoffee.com/jordyg
