// Mocks generated by Mockito 5.4.4 from annotations
// in tn_bottom_sheet_navigator/test/core/tn_bottom_sheet_trigger_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tn_bottom_sheet_navigator/core/entities/tn_bottom_sheet_route.dart'
    as _i5;
import 'package:tn_bottom_sheet_navigator/core/tn_router.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TnRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockTnRouter extends _i1.Mock implements _i2.TnRouter {
  @override
  _i3.Stream<List<_i4.Widget>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<List<_i4.Widget>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.Widget>>.empty(),
      ) as _i3.Stream<List<_i4.Widget>>);

  @override
  bool get canPop => (super.noSuchMethod(
        Invocation.getter(#canPop),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isOpened => (super.noSuchMethod(
        Invocation.getter(#isOpened),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get count => (super.noSuchMethod(
        Invocation.getter(#count),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setRoutes(List<_i5.TnBottomSheetRoute>? routes) => super.noSuchMethod(
        Invocation.method(
          #setRoutes,
          [routes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void go(
    String? path, {
    Map<String, dynamic>? params,
    required _i4.BuildContext? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #go,
          [path],
          {
            #params: params,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void push(
    String? path, {
    Map<String, dynamic>? params,
    required _i4.BuildContext? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #push,
          [path],
          {
            #params: params,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pop() => super.noSuchMethod(
        Invocation.method(
          #pop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
